spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_directory
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 588305069764-6k8hr0honuoiqmis0dbdi1rklp2tibbi.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
